<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
* Each input layer corresponds to a feature

### Hidden Layer:
* Layer between the input and output layer. I consider this the "black box" of a black box machine.

### Output Layer:
* Returns input modified by hidden layers. 

### Neuron:
* A neuron is contained within each layer of a neural network. They calculate the weighted sum of inputs and weights, add in the bias term and then run an activation function.

### Weight:
* Transforms the input data within hidden layers.

### Activation Function:
* Essentially it is the output of the neural network.

### Node Map:
* idk

### Perceptron:
* A single layer neural network.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [9]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [11]:
import numpy as np

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
  sx = sigmoid(x)
  return sx * (1 - sx)

In [16]:
## Set random weights for the inputs

np.random.seed(10)

weights = 2 * np.random.random((3, 1)) - 1
weights

array([[ 0.54264129],
       [-0.9584961 ],
       [ 0.26729647]])

In [18]:
# Calculate weighted sum of inputs and weights
inputs = np.array([data['x1'],
                   data['x2'],
                   data['y']])

correct_outputs = [[1], [1], [1], [0]]

weighted_sum = np.dot(inputs.T, weights)

In [19]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.56642907],
       [0.69209624],
       [0.33376626],
       [0.39750908]])

In [20]:
error = correct_outputs - activated_output
error

array([[ 0.43357093],
       [ 0.30790376],
       [ 0.66623374],
       [-0.39750908]])

In [22]:
adjustments = error * sigmoid_derivate(weighted_sum)
print("------ Adjustments ------")
print(adjustments)
print("\n")
print("------ Weights ------")
print(weights)

------ Adjustments ------
[[ 0.10647946]
 [ 0.06561399]
 [ 0.14814796]
 [-0.09520168]]


------ Weights ------
[[ 0.54264129]
 [-0.9584961 ]
 [ 0.26729647]]


In [23]:
weights += np.dot(inputs, adjustments)

print("------ New Weights ------")
print(weights)

------ New Weights ------
[[ 0.5130536 ]
 [-0.90554982]
 [ 0.58753789]]


In [24]:
# Update weights

for iteration in range(10_000):
  weighted_sum = np.dot(inputs.T, weights)
  activated_output = sigmoid(weighted_sum)
  error = correct_outputs - activated_output
  adjustments = error * sigmoid_derivate(weighted_sum)
  weights += np.dot(inputs, adjustments)

print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)


Weights after training
[[-2.40688139]
 [-2.41393431]
 [ 7.49077826]]
Output after training
[[0.99944206]
 [0.99384212]
 [0.99379881]
 [0.00799617]]


In [25]:
print("Correct Outputs")
print(correct_outputs)

Correct Outputs
[[1], [1], [1], [0]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [31]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
print(diabetes.shape)
diabetes.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [34]:
df = diabetes.copy()

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [35]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(df)[:-1]

X = df[feats].values

y = df['Outcome'].values

# Normalizer - get values between 0 and 1
normalizer = Normalizer()

X = normalizer.transform(X)

In [36]:
print(f"X size: {len(X)} \ny size: {len(y)}")
print(f"\nX type: {type(X)} \ny type: {type(y)}")

X size: 768 
y size: 768

X type: <class 'numpy.ndarray'> 
y type: <class 'numpy.ndarray'>


In [47]:
 ##### Update this Class #####

class Perceptron:
    
  def __init__(self, niter = 10):
      self.niter = niter
  
  def __sigmoid(self, x):
      return 1 / (1 + np.exp(-x))
  
  def __sigmoid_derivative(self, x):
      sx = self.__sigmoid(x)
      return sx * (1-sx)

  def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """
  
    # Randomly Initialize Weights
    np.random.seed(10)

    weights = 2 * np.random.random((len(X),1)) - 1

    for i in range(self.niter):
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(X.T, weights)

        # Activate!
        activated_output = self.__sigmoid(weighted_sum)

        # Cac error
        error = y - activated_output

        # Update the Weights - get adjustments - consider adding a learning
        # rate
        adjustments = error * self.__sigmoid_derivative(weighted_sum)

        weights = weights + (np.dot(X, adjustments))

    return weights, error

  def predict(self, X, y):
    """Return class label after unit step"""
    np.random.seed(10)
    weights = 2 * np.random.random((len(X),1)) - 1

    for i in range(self.niter):
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(X.T, weights)

        # Activate!
        activated_output = self.__sigmoid(weighted_sum)

        # Cac error
        error = y - activated_output

        # Update the Weights - get adjustments
        adjustments = error * self.__sigmoid_derivative(weighted_sum)

        weights = weights + (np.dot(X, adjustments))
    
    return activated_output

In [48]:
perceptron = Perceptron()

In [49]:
perceptron.fit(X, y)

(array([[ 0.69859944,  0.50188433,  0.69859944, ...,  0.50188433,
          0.69859944,  0.50188433],
        [-0.775174  , -0.97304068, -0.775174  , ..., -0.97304068,
         -0.775174  , -0.97304068],
        [ 0.36091837,  0.22093047,  0.36091837, ...,  0.22093047,
          0.36091837,  0.22093047],
        ...,
        [ 0.08438265, -0.0666136 ,  0.08438265, ..., -0.0666136 ,
          0.08438265, -0.0666136 ],
        [ 0.53628534,  0.40293163,  0.53628534, ...,  0.40293163,
          0.53628534,  0.40293163],
        [ 0.45643412,  0.26578012,  0.45643412, ...,  0.26578012,
          0.45643412,  0.26578012]]),
 array([[ 6.89779065e-02, -3.38717028e-01,  6.89779065e-02, ...,
         -3.38717028e-01,  6.89779065e-02, -3.38717028e-01],
        [ 0.00000000e+00, -3.79326414e-10,  0.00000000e+00, ...,
         -3.79326414e-10,  0.00000000e+00, -3.79326414e-10],
        [ 2.22044605e-16, -3.67841820e-08,  2.22044605e-16, ...,
         -3.67841820e-08,  2.22044605e-16, -3.67841820e-

In [50]:
perceptron.predict(X, y)

array([[9.31022094e-01, 3.38717028e-01, 9.31022094e-01, ...,
        3.38717028e-01, 9.31022094e-01, 3.38717028e-01],
       [1.00000000e+00, 3.79326414e-10, 1.00000000e+00, ...,
        3.79326414e-10, 1.00000000e+00, 3.79326414e-10],
       [1.00000000e+00, 3.67841820e-08, 1.00000000e+00, ...,
        3.67841820e-08, 1.00000000e+00, 3.67841820e-08],
       ...,
       [9.99999940e-01, 5.67599225e-04, 9.99999940e-01, ...,
        5.67599225e-04, 9.99999940e-01, 5.67599225e-04],
       [5.60405527e-01, 4.74606053e-01, 5.60405527e-01, ...,
        4.74606053e-01, 5.60405527e-01, 4.74606053e-01],
       [9.99999990e-01, 7.64866368e-04, 9.99999990e-01, ...,
        7.64866368e-04, 9.99999990e-01, 7.64866368e-04]])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?